nameOverride: "" # (Optional) Override default chart name
fullnameOverride: "" # (Optional) Override full default chart name

config:
 name : ""

# Uala Custom config
nodeSelector:
  eks.amazonaws.com/nodegroup: "transact"
  
tolerations:
  - key: "dedicated.uala"
    operator: "Equal"
    value: "transact"
    effect: "NoSchedule"

externalSecrets:
  enabled: true
  secretName: "dev/eks/transact-tst/externals"

# Financial Inclusion
deployFI:
  enabled: false # Deploy Temenos Financial Inclusion

# ATM Framework
deployATM:
  enabled: false # Deploy Temenos ATM Framework

# TemnLogger requirement
logstash:
  enabled: false # Deploy Logstash, required by ther TemnLogger

appReplicaCount: 1 # Transact app pod replicas
webReplicaCount: 1 # Transact web pod replicas 
apiReplicaCount: 1 # Transact API pod replicas
isoReplicaCount: 1 # ISO pod replicas
logstashReplicaCount: # Logstash pod replicas
edgeProp: SystemTestProperties # Configuration modes for UXP Browser. Accepted values: SystemTestProperties, ProductionProperties

appVersion: "" # (Optional) Transact version to be used in all image tags in the format {.Values.image.app.repository}:{.Values.image.app.version.}.{.Values.image.app.tag}
environment: "eks" # Deployment environment. Accepted values: aks, eks - for Azure Kubernetes Service and AWS Elastic Kubernetes Service respectively.

podSecurityPolicy:
  enabled: false # Optional pod security policy to ensure Temenos pods run with with minimal permissions e.g. non-root. Note: PodSecurityPolicies are deprecated as of Kubernetes v1.21 and removed in v.1.25.

serviceAccount:
  app: "" # Transact app service account. If value is blank, the service account will be created. To use an existing service account, set the name here.
  web: "" # Transact web service account. If value is blank, the service account will be created. To use an existing service account, set the name here.
  api: "" # Transact API service account. If value is blank, the service account will be created. To use an existing service account, set the name here.

iam:
  dbAccessRoleArn: "" # ARN of existing IAM role to be attached to the Transact app service account to grant rds-db:connect permission to enable the token generation by the AWS JDBC Wrapper for DB authentication. Only used if app service account name is not set above, otherwise if app service account name is provided, it is assumed an IAM role is attached granting adequate permissions to the RDS instance.

image:
  pullPolicy: IfNotPresent # Pull policy for images.
  pullSecret: "" # (Optional) Image pull secret.
  app:
    repository: 471112605010.dkr.ecr.us-east-1.amazonaws.com/transact-app # App image repository.
    tag: "R24.1.5.3" # App image tag.
  web:
    repository: 471112605010.dkr.ecr.us-east-1.amazonaws.com/transact-web # Web image repository.
    tag: "R24.1.5" # Web image tag.
  api:
    repository: 471112605010.dkr.ecr.us-east-1.amazonaws.com/transact-api # API image repository.
    tag: "R24.1.5" # API image tag.
  # ATM Framework requirement
  iso:
    repository: transact-iso # ISO image repository.
    tag: "" # ISO image tag.
  # TemnLogger requirement
  logstash:
    repository: tem-logstash # Logstash image repository.
    tag: "" # Logstash image tag.

tafjee:
  OLTP_ACTIVE: "true" # Online transaction processing active. true dictates that this Transact instance will serve the frontend applications. false will make it a Transact batch pod.
  SERVICE_ACTIVE: "false" # Run the Transact pod as a batch service.

apiIp: "" # (Optional) Set the API load balancer IP address.

component:
  name: "transact" # Specifies the Temenos component. Accepted values: transact, lending. Setting this will apply custom network policies with a default deny-all posture.

database:
  type: "PostgreSQL" # Database Type: AzureSQL, PostgreSQL, PostgreSQLawsWrapper, Yugabyte or Oracle
  user: "t24-tst" # Databse username
  # password: "" # Databse password - not required if using the PostgreSQLawsWrapper database option.
  host: "transact-db.dev.corebanking.uala.mx" # Database hostname.
  # encryptedPassword: "" # Encrypted database password value generated using the EncryptionUtility JAR found in the UXPB Tools package. Required if UXP is deployed and the PostgreSQLawsWrapper database type is not being used.
  port: "5432" # Database port number
  database: "transact-tst" # Database schema name

mq: 
  connectionstring: "ssl://b-920bb496-96e1-4e29-9f4a-4bf46ac66dea-1.mq.us-east-1.amazonaws.com:61617" # ActiveMQ connection string
  user: "transactjmuser-tst" # ActiveMQ user
  # password: "" # ActiveMQ password
  # host:
  # port:

app:
  user: "" # Transact username for UXP artefact connectivity
  # password: "" # Transact user password for UXP artefact connectivity
  
service:
  port: 8080 # WildFly HTTP port
  httpsPort: 8443 # WildFly HTTPS port

requests:
  app:
    cpu: "1.5"
    memory: "10G"
  web: 
    cpu: "1.5"
    memory: "6G"
  iso: 
    cpu: "1"
    memory: "6G"
  api: 
    cpu: "1.5"
    memory: "8G"
  logstash:
    cpu: "200m"
    memory: "1G"
limits:
  app: 
    cpu: "1.5"
    memory: "10G"
  web:
    cpu: "1.5"
    memory: "6G"
  iso:
    cpu: "1"
    memory: "6G"
  api:
    cpu: "2"
    memory: "12G"
  logstash:
    cpu: "200m"
    memory: "2G"

ingress:
  enabled: true # Deploy ingress to expose Transact services externally from the cluster
  controller: "awsalbcontroller" # Ingress controller to expose the Transact services. Accepted values: awsalbcontroller, nginx or agic
  usePrivateIp: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/inbound-cidrs: 10.10.25.0/24, 10.210.50.59/32, 10.210.32.0/19, 10.205.192.0/19
    external-dns.alpha.kubernetes.io/hostname: transact-tst.dev.corebanking.uala.mx
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:us-east-1:471112605010:certificate/3258cb38-83dd-43be-b828-d9a573b385c8'
  paths:
  - path: /TAFJ*
    service: "-app-svc"
  - path: /axis2*
    service: "-app-svc"
  - path: /TAFJCobMonitor*
    service: "-app-svc"
  - path: /tb-server*
    service: "-app-svc"    
  - path: /dsf-iris*
    service: "-app-svc"
  - path: /dsf-transact*
    service: "-app-svc"
  - path: /dsf-uxp*
    service: "-app-svc"
  dedicatedapipath:
  - path: /irf*
    service: "-lb"
  - path: /infinity*
    service: "-lb"
  - path: /mxmb*
    service: "-lb"
  queuelessapppath:
  - path: /irf*
    service: "-app-svc"
  - path: /infinity*
    service: "-app-svc"
  transactexplorerpath:
  - path: /transact-explorer-wa*
    service: "-svc"  
  browserpath:
  - path: /BrowserWeb*
    service: "-svc"
  - path: /Browser*
    service: "-svc"

autoscaling:
  enabled: true # Enable autoscaling for the Transact pods using the Horizontal Pod Autoscaler
  minReplicas: 1 # Minimum number of Transact pods if autoscaling is enabled
  maxReplicas: 5 # Maximum number of Transact pods if autoscaling is enabled
  targetCPUUtilizationPercentage: 75 # Pod CPU utilisation value at which more replicas will be created to distribute load.

mount:
  path: "/shares/"


volumes:
  name: "transact-volume"
  claimname: "transact-tst-temenos-transact-efs-pvc"
  fileSystemId: "fs-09d410d4c25c7c11d"
  fileSystemAPId: "fsap-05fb076cca1bd7feb"
  capacityStorage: 5Gi
  requestsStorage: 5Gi
  mounttargetip: "10.210.37.115"
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/"


gremlinIPblock: ""

jboss:
  MDB_POOL_MAX: "6" # Maximum MDB pool size.
  DB_POOL_MIN: "10" # Minimum database pool size
  DB_POOL_MAX: "100" # Maximum database pool size
  MAX_POOL_SIZE: "200" # JMS Connection factory pool size
  MAX_THREAD_COUNT: "200"
  IDLE_TIMEOUT_VALUE: "1"
  # JBOSS_PWD: "" # Password for application server console admin user
  console:
    exposed: true # Expose the application server console port in the app

uxp:
  debugLogs: false # Enable UXP debug logs

ssl:
  enabled: false # Use SSL for the Transact deployments.
  filename: "" # SSL certificate file name present in the ssl directory within this chart.
  password: "" # SSL certificate password
  rootCertName: "" # SSL certificate root certificate name

redis:
  enabled: false # Use Redis for the TAFJ cache.
  host: "" # Redis hostname
  keys: "" # Redis password

keycloak:
  api:
    enabled: false # Enable Keycloak for the API deployment
  enabled: false # Enable Keycloak for Transact web and app
  pkencoded: "" # Base64 encoded Keycloak Transact realm public key
  clientsecret: ""
  redirecturi: ""
  issuer: "" # Keycloak Transact realm URL
  clientid: "" # ID of UXP Browser client in KeyCloak
  principalclaim: "" # Name of Transact sign-on-name user attribute in Keycloak
  tokenendpoint: "" # Keycloak transact realm token end point URL
  pkcertencoded: ""
  authzendpoint: "" # Keycloak Transact realm authorization end point URL
  logoutendpoint: ""
  pkjwksuri: ""

akv:
  enabled: false # Azure KeyVault, not used for AWS EKS deployments
  
deployQueueless:
  enabled: false
  
deployTE:
  enabled: true
  TB_HELPTEXT_LOCATION: "../../HELP.TEXT/HelpText/"
  TE_TB_SERVER_URL: "https://transact-tst.dev.corebanking.uala.mx/tb-server"
  
CustomJavaOpts:
  APP:
    enabled: true
    JavaOpts: ' -Ddsf.iris18.host=http://transact-tst-temenos-transact-app-svc:8080/dsf-iris
                -Ddsf.catalogService.host=http://transact-tst-temenos-transact-app-svc:8080/irf-t24catalog-services
                -Ddsf.transactConn.api.security.context="MB.OFFICER/123456"
                -Ddsf.transactConn.api.security.context.encrypted=false
                -DDSF_CAPABILITY_DSF_TRANSACT_URL=http://transact-tst-temenos-transact-app-svc:8080/dsf-transact
                -DDSF_CAPABILITY_IRF_EXT_URL=http://transact-tst-temenos-transact-app-svc:8080/irf-extension-api
                -DDSF_CAPABILITY_IRF_PROVIDER_URL=http://transact-tst-temenos-transact-api-svc:8080/irf-provider-container
                -Ddsf.package.extensionRegistration.t24data.api=http://transact-tst-temenos-transact-app-svc:8080/dsf-transact/api/v1.0.0/packager/t24data/extensionRegistration '
  API:
    enabled: false
    JavaOpts: 
  WEB:
    enabled: false
    JavaOpts: -Dbrowser.options.dynamicIRIS.rpService=http://utptransact03-temenos-transact-app-svc.utptransact03.svc.cluster.local:8080/irf-rp-services -Dbrowser.options.god.catalogService=http://utptransact03-temenos-transact-app-svc.utptransact03.svc.cluster.local:8080/irf-t24catalog-services -Dbrowser.options.resourceServer.url=http://utptransact03-temenos-transact-app-svc.utptransact03.svc.cluster.local:8080/ResourceServer -Dbrowser.options.remoteAuth.url=http://utptransact03-temenos-transact-app-svc.utptransact03.svc.cluster.local:8080/Authenticator/auth/logon

meter:
  host: localhost
  port: 4317
  jmx: false

tracer:
  host: localhost
  port: 4317
  runtime: JVM

temnmonitor:
 enabled: false