# Default values for workbench-uux.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: workbench-uux

environment: "eks"

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  pullSecret: ""
  app:
    repository: workbench-uux
    tag: 202307.0

serviceAccount:
  # Specifies whether a service account should be 
  enabled: true
   # The name of the service account to use.
  # If not set then service account workbench-uux-sa will be created 
  name: ""

service:
  type: ClusterIP
  http_port: "80"
  https_port: "443"
  
env:
  nodeEnv: "production" 
  httpPort: "8080"
  httpsEnabled: false
  httpsPort: "8443"
  ssl_cert_content_b64enc: ""
  ssl_cert_password: ""
  wbToolsBaseUrl: "http://workbench:8080/wb-tools"
  wbProfile: "TRANSACT-EF"
  wbToolsSwaggerContextPath: "/v1.0.0/swagger.json"
  wbToolsHealthContextPath: "/api/v1.0.0/health/core"
  contextPath: "/wb-uux"
  authProvider: "OIDC"   # OIDC, BASIC
  loginMode: "KEYCLOAK"  # KEYCLOAK , CUSTOM
  oidcAuthServerUrl: "http://lauwinds1.temenosgroup.com:8180/auth"
  oidcClientId: "workbench2.0"
  oidcRealmName: "DSFPackager"
  oidcClientSecret: ""
  otelExporterEndpoint: "http://otel-collector:4317"
  otelServiceName: "workbench"
  otelPropagators:  "tracecontext,baggage,jaeger"
  allowedOrigins: "*"
  sessionTimeoutMinutes: "60"
  cookieSecured: "false"
  maxBodyRequestSize: "5mb"
  maxFileUploadSizeMb: "100"
  
tls:
  crt: ""
  key: ""

resources: 
  limits:
    cpu: "2"
    memory: "6G"
  requests:
    cpu: "2"
    memory: "3G"
    
ingress:
  enabled: true
  controller: ""
  annotations: {}
  usePrivateIp: true
  gatewayPrivateIP: ""
  domainName: ""
  hosts: ""
  paths:
  - path: /wb-assets/*
  - path: /wb-uux/*

  
networkpolicy:
  # if true then network policy will be deployed in workbench-uux namespace
  enabled: true