apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workbenchtools.fullname" . }}{{ "-config-secret" }}
type: Opaque
data:
  gitAdminAccessToken: {{ .Values.env.gitAdminAccessToken |  b64enc | quote }}
  artifactoryKey: {{ .Values.env.artifactoryKey | b64enc | quote }}
  kafkaSecurityPassword: {{ .Values.env.kafkaSecurityPassword | b64enc | quote }}
  {{- if .Values.env.quarkusHttpsEnabled }}
  ssl_cert_password: {{ .Values.env.ssl_cert_password | b64enc | quote }}
  {{- end }}
---  
{{- if eq .Values.environment "aks" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workbenchtools.fullname" . }}{{ "-secret" }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.fileShare.StorageAccount |  b64enc | quote }}
  azurestorageaccountkey: {{ .Values.fileShare.StorageKey | b64enc | quote }}
{{- end }}
---
{{- if .Values.env.quarkusHttpsEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workbenchtools.fullname" . }}{{ "-ssl-secret" }}
type: Opaque
data:
  ssl_cert.pfx: {{ .Values.env.ssl_cert_content_b64enc | quote }}
{{- end }}
