{{- if eq .Values.environment "eks" }}
{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dsf-workbench-tools.serviceAccountName" . | quote }}
  labels:
    app.kubernetes.io/name: {{ include "workbenchtools.name" . }}
    helm.sh/chart: {{ include "workbenchtools.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
{{- end }}