apiVersion: v1
kind: Service
metadata:
  name: {{ include "workbenchtools.fullname" . }}
  labels:
    {{- include "workbenchtools.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.env.quarkusHttpsEnabled }}
    - port: {{ .Values.service.https_port | default 443 }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
    - port: {{ .Values.service.http_port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "workbenchtools.selectorLabels" . | nindent 4 }}
