apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-stg
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra-prj
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.12.1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true