{{- if eq .Values.environment "eks" }}
{{- if not .Values.serviceAccount.app }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceaccount.app.name" . | quote }}
  labels:
    app.kubernetes.io/name: {{ include "transact.name" . }}{{ "-app" }}
    helm.sh/chart: {{ include "transact.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.iam.dbAccessRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iam.dbAccessRoleArn }}
  {{- end }}
{{- end }}
{{- end }}