{{- if .Values.deployATM.enabled }}    #This file is used to deploy ATM framework and it is meant to be client specific requirement.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transact.fullname" . }}{{ "-iso" }}
  labels:
    app.kubernetes.io/name: {{ include "transact.name" . }}{{ "-iso" }}
    helm.sh/chart: {{ include "transact.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.isoReplicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "iso.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "iso.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "transact.name" . }}{{ "-iso" }}
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "transact.name" . }}{{ "-iso" }}
              topologyKey: topology.kubernetes.io/hostname
            weight: 100
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "iso.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        envFrom:
        - configMapRef:
            name: jboss-config
        env:
        - name: JMS_URL
          valueFrom:
            configMapKeyRef:
              name: transact-config
              key: jmsurl
        - name: JMS_USER
          valueFrom:
            configMapKeyRef:
              name: transact-config
              key: jmsuser
        {{- if .Values.mq.password }}
        - name: JMS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: externals
              key: jms_password
        {{- end }}
        - name: JBOSS_PWD
          valueFrom:
            secretKeyRef:
              name: externals
              key: jbossAdminPassword
        - name: WWW_PORT
          value: "8080"
        - name: BRP_HOME
          value: "/srv/Temenos"
        - name: EDGE_PROP
          value: {{ .Values.edgeProp | default "SystemTestProperties" }}
        {{- if .Values.ssl.enabled }}
        - name: SSL_FILENAME
          valueFrom:
            configMapKeyRef:
              name: transact-config
              key: ssl_filename
        - name: SSL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: externals
              key: ssl_password
        {{- end }}
        {{- with .Values.env }}
          {{- toYaml . | nindent 10 }}
        {{- end }}              
        resources:
          requests:
            cpu: {{ .Values.requests.iso.cpu }}
            memory: {{ .Values.requests.iso.memory }}
          limits:
            cpu: {{ .Values.limits.iso.cpu }}
            memory: {{ .Values.limits.iso.memory }}
        ports:
        - name: iso
          containerPort: 8080
          protocol: TCP
        {{- if .Values.ssl.enabled }}
        - name: https
          containerPort: 8443
          protocol: TCP
        {{- end }} 
        readinessProbe:
          httpGet:
            path: /
            {{- if .Values.ssl.enabled }}
            port: 8443
            scheme: HTTPS
            {{- else }}
            port: 8080
            {{- end }}
          periodSeconds: 30
          timeoutSeconds: 30
        volumeMounts:
          {{- if .Values.ssl.enabled }}
          - name: ssl-cert
            mountPath: {{ "/opt/jboss/wildfly/standalone/configuration/" }}{{ .Values.ssl.filename }}
            subPath: {{ .Values.ssl.filename }}
          {{- end }}
          {{- if .Values.akv.enabled }}
          - name: secrets-store
            mountPath: "/mnt/secrets-store"
            readOnly: true
          {{- end }}
      volumes:
        {{- if .Values.ssl.enabled }}
        - name: ssl-cert
          secret:
            secretName: ssl-secret
        {{- end }}
        {{- if .Values.akv.enabled }}
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "transact.fullname" . }}{{ "-kvsecret" }}
        {{- end }}
{{- end }}