{{- if .Values.akv.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "transact.fullname" . }}{{ "-kvsecret" }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.akv.aksIdentityID }}"             
    keyvaultName: "{{ .Values.akv.name }}"
    objects:  |
      array:
        - |
          objectName:  {{ .Values.database.password }}          
          objectType: secret
        {{- if .Values.ssl.enabled }}                                      
        - |
          objectName: {{ .Values.ssl.password }}
          objectType: secret
        {{- end }}
        - |
          objectName: {{ .Values.jboss.JBOSS_PWD }}
          objectType: secret
        - |
          objectName: {{ .Values.app.password }}
          objectType: secret
        - |
          objectName: {{ .Values.database.encryptedPassword }}
          objectType: secret
        {{- if .Values.keycloak.enabled }}                                      
        - |
          objectName: {{ .Values.keycloak.clientsecret }}
          objectType: secret
        - |
          objectName: {{ .Values.keycloak.pkencoded }}
          objectType: secret
        {{- end }}
    tenantId: "{{ .Values.akv.tenantID }}"            
  secretObjects:                             
  - secretName: externals  
    data:
    - key: db_password
      objectName: {{ .Values.database.password }}
    {{- if .Values.ssl.enabled }}
    - key: ssl_password
      objectName: {{ .Values.ssl.password }}
    {{- end }}
    - key: jbossAdminPassword
      objectName: {{ .Values.jboss.JBOSS_PWD }}
    - key: app_password
      objectName: {{ .Values.app.password }} 
    - key: encryptedPassword
      objectName: {{ .Values.database.encryptedPassword }}      
    {{- if .Values.keycloak.enabled }}     
    - key: keycloakclientsecret
      objectName: {{ .Values.keycloak.clientsecret }}
    - key: keycloakpkencoded
      objectName: {{ .Values.keycloak.pkencoded }}
    {{- end }}
    type: Opaque
{{- end }}