{{- if not .Values.deployQueueless.enabled -}}
{{- if eq .Values.environment "eks" }}
{{- if not .Values.serviceAccount.api }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceaccount.api.name" . | quote }}
  labels:
    app.kubernetes.io/name: {{ include "transact.name" . }}{{ "-app" }}
    helm.sh/chart: {{ include "transact.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
{{- end }}
{{- end }}