
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "transact.fullname" . }}{{ "-efs-pvc" }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "transact.fullname" . }}{{ "-efs-sc" }}
  resources:
    requests:
      storage: {{ .Values.volumes.requestsStorage }}
