{{- if eq .Values.environment "aks" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transact.name" . }}{{ "-secret" }}
type: Opaque
data:
  azurestorageaccountname: {{.Values.secrets.azurestorageaccountname | b64enc }}
  azurestorageaccountkey: {{.Values.secrets.azurestorageaccountkey | b64enc }}
{{- end }}