apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-stg
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: infra-prj
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.5
    helm:
      values: |
        provider:
          name: aws
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::471112832974:role/eks_irsa_external-dns_mex-stage
        env:
          - name: AWS_DEFAULT_REGION
            value: us-east-1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true