# Default values for workbenchtools.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: "minikube"

image:
  pullPolicy: Never
  pullSecret: ""
  tools:
    repository: dsf-workbench/wbtools
    tag: latest

service:
  type: ClusterIP
  http_port: "80"
  https_port: "443"
  
env:
  quarkusHttpPort: "8080"
  quarkusInsecureRequests: "enabled" # enabled, disabled, redirect
  quarkusHttpsEnabled: false # true, false
  quarkusHttpsPort: "8443"
  ssl_cert_content_b64enc: "" # base64 encoded ssl certificate file (pfx) content
  ssl_cert_password: "" # password for the  ssl certificate 
  ssl_cert_filetype: "PKCS12" # JKS, JCEKS, P12, PKCS12, PFX
  wbToolsConfigProfile: "SAAS" # DEV, SAAS, UTP
  wbToolsBootstrapProfiles: "false" # DEV only
  wbToolsContextPath: "/wb-tools"
  wbToolsLogLevel: "ERROR" # INFO, WARN, ERROR
  wbToolsHealthCheckInterval: "10m"
  wbToolsConfigProvider: "nitrite_db" # nitrite_db (DEV Only), generic_config, dsf_settings
  wbToolsConfigServerUrl: ""
  wbToolsBuildDbLimit: "10"
  otelEnabled: "false"
  otelExporterEndpoint: ""
  saasWorkbenchInstance: "24d2028c-ae87-4069-a624-66089d957ef9"
  saasWorkbenchBlueprint: "14d2028c-ae87-4069-a624-66089d957ef9"
  authProvider: "oidc"   # oidc, basic
  oidcAuthServerUrl: "http://lauwinds1.temenosgroup.com:8180/auth/realms/DSFPackager"   # none for basic auth
  oidcClientId: "wbgitfs"
  gitProvider: "gitlab" # gitlab, bitbucket, none
  gitServerUrl: "http://10.20.100.35"
  gitProject: "pkk-l3jav-demo"
  gitRepository: "none" # only incase of bitbucket
  gitAdminAccessToken: "gjkF8zCd5dkBKTN-oi7o"
  gitRepoRoot: "/wbgitfs/repos"
  manageGitUsers: "true"
  manageGitProjects: "true"
  manageL3Binaries: "false"
  repoProvider: "none" # jfrog, local, none
  artifactoryBaseUrl: ""
  artifactoryKey: ""
  tenantArtifactoryRepo: ""
  notificationProvider: "none" # kafka, none
  kafkaBootstrapServers: "core-shs-notifications-euw1.servicebus.windows.net:9093"
  kafkaProducerTopic: "sbx-notification-engine"
  kafkaSecurityProtocol: "SASL_SSL"
  kafkaSaslMechanism: "PLAIN"
  kafkaSecurityPassword: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="Endpoint=sb://core-shs-notifications-euw1.servicebus.windows.net/;SharedAccessKeyName=producer;SharedAccessKey=H9UWf/lrNasndB5JHztDSgDWLnznWP/Rwq+Y8uhoASg=;EntityPath=sbx-notification-engine"  
  
fileShare:
  storageClassName: workbenchtools-azurefile
  pvcName: workbenchtools-pvc
  secretName: workbenchtools-secret
  storageSize: 1Gi
  StorageAccount: ""
  StorageKey: ""
  shareName: "wb-data"

resources: 
  limits:
    cpu: "1"
    memory: "2G"
  requests:
    cpu: "1"
    memory: "1G"
    
ingress:
  enabled: true
  controller: "nginx"
  annotations: {}
  usePrivateIp: true
  gatewayPrivateIP: ""
  domainName: ""
  hosts: "dsf.temenos"
  paths:
  - path: /wb-tools/*