apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-stg
  namespace: argocd
spec:
  project: infra-prj
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.10.3
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true