{{- if eq .Values.environment "eks" }}
{{- if .Values.networkpolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "workbench-uux.fullname" . }}{{ "-policy-deny-all" }}
  labels:
    app.kubernetes.io/name: {{ include "workbench-uux.name" . }}
    helm.sh/chart: {{ include "workbench-uux.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "workbench-uux.fullname" . }}{{ "-workbench-uux" }}
  labels:
    app.kubernetes.io/name: {{ include "workbench-uux.name" . }}
    helm.sh/chart: {{ include "workbench-uux.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  podSelector:
    matchLabels:
      {{- include "workbench-uux.selectorLabels" . | nindent 6 }}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
{{- end }}
{{- end }}