{{- if .Values.env.httpsEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workbench-uux.fullname" . }}{{ "-ssl-secret" }}
type: Opaque
data:
  ssl_cert.pfx: {{ .Values.env.ssl_cert_content_b64enc | quote }}
  ssl_cert_password: {{ .Values.env.ssl_cert_password | b64enc | quote }}
{{- end }}
