{{- if eq .Values.environment "eks" }}
{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workbench-uux.serviceAccountName" . | quote }}
  labels:
    app.kubernetes.io/name: {{ include "workbench-uux.name" . }}
    helm.sh/chart: {{ include "workbench-uux.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
{{- end }}